server:
  port: 8080
  address: localhost

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: sa
    password:

  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations: